apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    devEnvApprovers:
    - umairbajwa
    environmentGitOwner: umairbajwa
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: gke
    registry: gcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "umairbajwa.net"
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: vault
  vault: {}
  webhook: lighthouse
